-- MySQL Script generated by MySQL Workbench
-- Sat Jun 28 17:24:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS doacoes;
use doacoes;
-- -----------------------------------------------------
-- Table `CategoriaDoItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CategoriaDoItem` ;

CREATE TABLE IF NOT EXISTS `CategoriaDoItem` (
  `idCategoriaDoItem` INT NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idCategoriaDoItem`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Doador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Doador` ;

CREATE TABLE IF NOT EXISTS `Doador` (
  `idDoador` INT NOT NULL,
  `Nome` VARCHAR(100) NULL,
  `CPF_CNPJ` VARCHAR(14) NULL,
  `E-mail` VARCHAR(50) NULL,
  `Telefone` VARCHAR(15) NULL,
  PRIMARY KEY (`idDoador`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Instituicao` ;

CREATE TABLE IF NOT EXISTS `Instituicao` (
  `CNPJ_Instituicao` CHAR(14) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Endereco` VARCHAR(100) NOT NULL,
  `Telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`CNPJ_Instituicao`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Receptor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Receptor` ;

CREATE TABLE IF NOT EXISTS `Receptor` (
  `idReceptor` INT NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  `CPF` CHAR(11) NULL,
  `Endereco` VARCHAR(100) NULL,
  `Composicao_familiar` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idReceptor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Doacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Doacao` ;

CREATE TABLE IF NOT EXISTS `Doacao` (
  `idDoacao` INT NOT NULL,
  `Data_da_doacao` DATE NULL,
  `ID_doador` INT NOT NULL,
  `CNPJ_instituicao` CHAR(14) NOT NULL,
  PRIMARY KEY (`idDoacao`),
  CONSTRAINT `fk_Doacao_Doador`
    FOREIGN KEY (`ID_doador`)
    REFERENCES `Doador` (`idDoador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doacao_Instituicao`
    FOREIGN KEY (`CNPJ_instituicao`)
    REFERENCES `Instituicao` (`CNPJ_Instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idx_Doacao_ID_doador` ON `Doacao` (`ID_doador`);
CREATE INDEX `idx_Doacao_CNPJ_instituicao` ON `Doacao` (`CNPJ_instituicao`);


-- -----------------------------------------------------
-- Table `ItemDoado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ItemDoado` ;

CREATE TABLE IF NOT EXISTS `ItemDoado` (
  `idItemDoado` INT NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  `Descricao` VARCHAR(100) NULL,
  `ID_categoria` INT NOT NULL,
  PRIMARY KEY (`idItemDoado`),
  CONSTRAINT `fk_ItemDoado_Categoria`
    FOREIGN KEY (`ID_categoria`)
    REFERENCES `CategoriaDoItem` (`idCategoriaDoItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idx_ItemDoado_ID_categoria` ON `ItemDoado` (`ID_categoria`);

-- -----------------------------------------------------
-- Table `Voluntario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Voluntario` ;

CREATE TABLE IF NOT EXISTS `Voluntario` (
  `CPF_Voluntario` CHAR(11) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Telefone` VARCHAR(15) NOT NULL,
  `CNPJ_instituicao` CHAR(14) NOT NULL,
  PRIMARY KEY (`CPF_Voluntario`),
  CONSTRAINT `fk_Voluntario_Instituicao`
    FOREIGN KEY (`CNPJ_instituicao`)
    REFERENCES `Instituicao` (`CNPJ_Instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idx_Voluntario_CNPJ_instituicao` ON `Voluntario` (`CNPJ_instituicao`);

-- -----------------------------------------------------
-- Table `TransacaoDeDoacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransacaoDeDoacao` ;

CREATE TABLE IF NOT EXISTS `TransacaoDeDoacao` (
  `idTransacaoDeDoacao` INT NOT NULL,
  `Data_da_entrega` DATE NULL,
  `ID_receptor` INT NOT NULL,
  PRIMARY KEY (`idTransacaoDeDoacao`),
  CONSTRAINT `fk_Transacao_Receptor`
    FOREIGN KEY (`ID_receptor`)
    REFERENCES `Receptor` (`idReceptor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idx_TransacaoDeDoacao_ID_receptor` ON `TransacaoDeDoacao` (`ID_receptor`);

-- -----------------------------------------------------
-- Table `ItensDaDoacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ItensDaDoacao` ;

CREATE TABLE IF NOT EXISTS `ItensDaDoacao` (
  `ID_doacao` INT NOT NULL,
  `ID_item_doado` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  `Data_de_validade` DATE NULL,
  PRIMARY KEY (`ID_doacao`, `ID_item_doado`),
  CONSTRAINT `fk_ItensDaDoacao_Doacao`
    FOREIGN KEY (`ID_doacao`)
    REFERENCES `Doacao` (`idDoacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItensDaDoacao_ItemDoado`
    FOREIGN KEY (`ID_item_doado`)
    REFERENCES `ItemDoado` (`idItemDoado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idx_ItensDaDoacao_ID_doacao` ON `ItensDaDoacao` (`ID_doacao`);
CREATE INDEX `idx_ItensDaDoacao_ID_item_doado` ON `ItensDaDoacao` (`ID_item_doado`);

-- -----------------------------------------------------
-- Table `ItensDaTransacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ItensDaTransacao` ;

CREATE TABLE IF NOT EXISTS `ItensDaTransacao` (
  `ID_item_doado` INT NOT NULL,
  `ID_transacao` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`ID_item_doado`, `ID_transacao`),
  CONSTRAINT `fk_ItensDaTransacao_ItemDoado`
    FOREIGN KEY (`ID_item_doado`)
    REFERENCES `ItemDoado` (`idItemDoado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItensDaTransacao_Transacao`
    FOREIGN KEY (`ID_transacao`)
    REFERENCES `TransacaoDeDoacao` (`idTransacaoDeDoacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idx_ItensDaTransacao_ID_item_doado` ON `ItensDaTransacao` (`ID_item_doado`);
CREATE INDEX `idx_ItensDaTransacao_ID_transacao` ON `ItensDaTransacao` (`ID_transacao`);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
