-- MySQL Script generated by MySQL Workbench
-- Sat Mar 15 17:02:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ALUNO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ALUNO` ;

CREATE TABLE IF NOT EXISTS `ALUNO` (
  `CPF` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `sexo` VARCHAR(1) NULL,
  `datanasc` DATE NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AREA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AREA` ;

CREATE TABLE IF NOT EXISTS `AREA` (
  `sigla` VARCHAR(5) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `superarea` VARCHAR(45) NULL,
  `AREA_sigla` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`sigla`, `AREA_sigla`),
  CONSTRAINT `fk_AREA_AREA1`
    FOREIGN KEY (`AREA_sigla`)
    REFERENCES `AREA` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_AREA_AREA1_idx` ON `AREA` (`AREA_sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `CURSO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CURSO` ;

CREATE TABLE IF NOT EXISTS `CURSO` (
  `sigla` VARCHAR(5) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `horas` INT NULL,
  `custo` DOUBLE NULL,
  `area` VARCHAR(45) NULL,
  `AREA_sigla1` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`sigla`, `AREA_sigla1`),
  CONSTRAINT `fk_CURSO_AREA1`
    FOREIGN KEY (`AREA_sigla1`)
    REFERENCES `AREA` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CURSO_AREA1_idx` ON `CURSO` (`AREA_sigla1` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `MATRICULA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MATRICULA` ;

CREATE TABLE IF NOT EXISTS `MATRICULA` (
  `curso` VARCHAR(5) NOT NULL,
  `aluno` VARCHAR(5) NOT NULL,
  `data` DATE NULL,
  `pago` TINYINT NULL,
  PRIMARY KEY (`curso`, `aluno`),
  CONSTRAINT `curso`
    FOREIGN KEY (`curso`)
    REFERENCES `CURSO` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `aluno`
    FOREIGN KEY (`aluno`)
    REFERENCES `ALUNO` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `aluno_idx` ON `MATRICULA` (`aluno` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `MODULO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MODULO` ;

CREATE TABLE IF NOT EXISTS `MODULO` (
  `sigla` VARCHAR(5) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `curso` VARCHAR(45) NULL,
  `CURSO_sigla` VARCHAR(5) NOT NULL,
  `CURSO_AREA_sigla1` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`sigla`, `CURSO_sigla`, `CURSO_AREA_sigla1`),
  CONSTRAINT `fk_MODULO_CURSO1`
    FOREIGN KEY (`CURSO_sigla` , `CURSO_AREA_sigla1`)
    REFERENCES `CURSO` (`sigla` , `AREA_sigla1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_MODULO_CURSO1_idx` ON `MODULO` (`CURSO_sigla` ASC, `CURSO_AREA_sigla1` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PROFESSOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROFESSOR` ;

CREATE TABLE IF NOT EXISTS `PROFESSOR` (
  `curso` VARCHAR(5) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`curso`, `CPF`),
  CONSTRAINT `curso`
    FOREIGN KEY (`curso`)
    REFERENCES `CURSO` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TOPICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TOPICO` ;

CREATE TABLE IF NOT EXISTS `TOPICO` (
  `modulo` VARCHAR(5) NOT NULL,
  `sigla` VARCHAR(5) NOT NULL,
  `horas` DOUBLE NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`sigla`, `modulo`),
  CONSTRAINT `modulo`
    FOREIGN KEY (`modulo`)
    REFERENCES `MODULO` (`sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `modulo_idx` ON `TOPICO` (`modulo` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
